name: Kotlin Multiplatform Tests
on: [push]

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: linuxX64Test
          - os: windows-latest
            target: mingwX64Test
          - os: macos-latest
            target: macosArm64Test
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run get request tests
        shell: bash
        run: |
          ./gradlew core:${{ matrix.target }} --tests "work.socialhub.kbsky.com.atproto.identity.ATProtoNativeTest.testResolveHandle"

      - name: Upload get test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: get-test-results-${{ matrix.target }}
          path: core/build/reports/tests/
